export const slides = [
  {
    id: 1,
    type: "image",
    src: "/images/heroImage1.jpeg",
    brand: "Kering",
    title: "Endless Narratives",
    link: "/kering",
    thumbnail: "/images/BAL_STORY_BRAND_DESKTOP_522c10a8f7.png",
  },
  {
    id: 2,
    type: "image",
    src: "/images/heroImage2.jpeg",
    brand: "Gucci",
    link: "/gucci",
    thumbnail:
      "/images/Logo_Bottega_Veneta_V2_sur_fond_blanc_pour_pastille_homepage_5a9791d903.jpeg",
  },
  {
    id: 3,
    type: "video",
    src: "/images/heroImage3.jpeg",
    brand: "Saint Laurent",
    link: "/saint-laurent",
    thumbnail: "/images/Logo_pastille_Brioni_Fond_Blanc_e04961a221.png",
  },
  {
    id: 4,
    type: "image",
    src: "/images/heroImage4.jpeg",
    brand: "Bottega Veneta",
    link: "/bottega-veneta",
    thumbnail: "/images/Mc_Queen_logo_pastille_blanc_8eb8a70911.png",
  },
  {
    id: 5,
    type: "image",
    src: "/images/heroImage5.png",
    brand: "Balenciaga",
    link: "/balenciaga",
    thumbnail: "/images/pastille_blanc_ginori_1735_9750923897.png",
  },
  {
    id: 6,
    type: "video",
    src: "/images/heroImage6.jpeg",
    brand: "McQueen",
    link: "/mcqueen",
    thumbnail: "/images/Pastille_Pomellato_blanc_sept_21_624dfd5f08.png",
  },
  {
    id: 7,
    type: "image",
    src: "/images/heroImage7.jpeg",
    brand: "Brioni",
    link: "/brioni",
    thumbnail: "/images/STORY_BRAND_DESKTOP_BOUCHERON_d3fa49a775.png",
  },
  {
    id: 8,
    type: "image",
    src: "/images/heroImage8.png",
    brand: "Boucheron",
    link: "/boucheron",
    thumbnail: "/images/dodo_pastille_blanc_mai2021_b80e37b61f.png",
  },
  {
    id: 9,
    type: "video",
    src: "/images/heroImage3.jpeg",
    brand: "Saint Laurent",
    link: "/saint-laurent",
    thumbnail: "/images/Logo_pastille_Brioni_Fond_Blanc_e04961a221.png",
  },
  {
    id: 10,
    type: "image",
    src: "/images/heroImage4.jpeg",
    brand: "Bottega Veneta",
    link: "/bottega-veneta",
    thumbnail: "/images/Mc_Queen_logo_pastille_blanc_8eb8a70911.png",
  },
  {
    id: 11,
    type: "image",
    src: "/images/heroImage5.png",
    brand: "Balenciaga",
    link: "/balenciaga",
    thumbnail: "/images/pastille_blanc_ginori_1735_9750923897.png",
  },
  {
    id: 12,
    type: "video",
    src: "/images/heroImage6.jpeg",
    brand: "McQueen",
    link: "/mcqueen",
    thumbnail: "/images/Pastille_Pomellato_blanc_sept_21_624dfd5f08.png",
  },
  {
    id: 13,
    type: "image",
    src: "/images/heroImage7.jpeg",
    brand: "Brioni",
    link: "/brioni",
    thumbnail: "/images/STORY_BRAND_DESKTOP_BOUCHERON_d3fa49a775.png",
  },
  {
    id: 14,
    type: "image",
    src: "/images/heroImage8.png",
    brand: "Boucheron",
    link: "/boucheron",
    thumbnail: "/images/dodo_pastille_blanc_mai2021_b80e37b61f.png",
  },
];