import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Others/Footer";
import { initTranslations } from '../i18n/initTranslations';
import TranslationsProvider from '../i18n/TranslationsProvider';

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'ar' }];
}

function isRtl(locale: string) {
  return ['ar', 'fa', 'he', 'ur'].includes(locale);
}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;
  const namespaces = ['common'];
  const { resources } = await initTranslations(locale, namespaces);
  return (
    <html lang={locale} dir={isRtl(locale) ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
         <TranslationsProvider locale={locale} resources={resources} namespaces={namespaces}>
          {children}
        </TranslationsProvider>
        <Footer />
      </body>
    </html>
  );
}
