import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Others/Footer";
import { initTranslations } from '../i18n/initTranslations';
import TranslationsProvider from '../i18n/TranslationsProvider';
import { ReactNode } from "react";

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'ar' }];
}

function isRtl(locale: string) {
  return ['ar', 'fa', 'he', 'ur'].includes(locale);
}
const geistSans = Roboto({
  subsets: ['latin'],
  weight: '400',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode
params: Promise<{ locale: string }>}) {

  const { locale } =await params
  const namespaces = ['common'];
  const { resources } = await initTranslations(locale, namespaces);

  
  return (
    <html lang={locale} dir={isRtl(locale) ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.className} antialiased`}
      >
        <Header />
         <TranslationsProvider locale={locale} resources={resources} namespaces={namespaces}>
          {children}
        </TranslationsProvider>
        <Footer />
      </body>
    </html>
  );
}
